- name: Configurar IPv6 Loopback1 en Cisco IOS XE
  hosts: routers
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Configurar dirección IPv6 y link-local en Loopback1
      ios_config:
        lines:
          - interface Loopback1
          - ipv6 address 3001:ABCD:ABCD:1::1/128
          - ipv6 address FE80::1 link-local
